### PR TITLE
Python and pytest compatibility fixes

### PR DESCRIPTION
**Pull request by ogajduse**
Various fixes to get the plugin compatible with the latest version of pytest and Python.

- - -
This change is [Reviewable](https://reviewable.io/reviews/pytest-dev/pytest-fixture-tools/7)

### CODE REVIEW

**Comment by ogajduse** [comment]
@bubenkoff Seems that you no longer contribute to the project. Could you please redirect me to someone who would be willing to help me getting this PR merged?

**Comment by bubenkoff** [comment]
@ogajduse invited you as maintainer, please also check another stall PR

**Comment by bubenkoff** [comment]
@ogajduse please also provide your pypi username so that I can add you as a maintainer there

**Comment by bubenkoff** [comment]
@ogajduse nevermind, found it's the same so I've proceed

**Comment by ogajduse** [comment]
Thank you. I accepted both invitations. 
I will try to do my best.

**Pull request merged**
